# Generated by Django 5.0.1 on 2024-01-18 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='position',
            field=models.CharField(choices=[('def', 'Defenseur'), ('mil', 'Milieu'), ('att', 'Attaquant'), ('gk', 'Gardien')], default='def', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='players',
            name='year_old',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(45)]),
            preserve_default=False,
        ),
    ]
